

export const SELLER_DETAILS_REQUEST = 'SELLER_DETAILS_REQUEST'
export const SELLER_DETAILS_SUCCESS = 'SELLER_DETAILS_SUCCESS'
export const SELLER_DETAILS_FAIL = 'SELLER_DETAILS_FAIL'
export const SELLER_DETAILS_RESET = 'SELLER_DETAILS_RESET'

export const SELLER_ORDER_LIST_REQUEST = 'SELLER_ORDER_LIST_REQUEST'
export const SELLER_ORDER_LIST_SUCCESS = 'SELLER_ORDER_LIST_SUCCESS'
export const SELLER_ORDER_LIST_FAIL = 'SELLER_ORDER_LIST_FAIL'
export const SELLER_ORDER_LIST_RESET = 'SELLER_ORDER_LIST_RESET'

export const SELLER_DELETE_REQUEST = 'SELLER_DELETE_REQUEST'
export const SELLER_DELETE_SUCCESS = 'SELLER_DELETE_SUCCESS'
export const SELLER_DELETE_FAIL = 'SELLER_DELETE_FAIL'

export const SELLER_PROFILE_UPDATE_REQUEST = 'SELLER_UPDATE_REQUEST'
export const SELLER_PROFILE_UPDATE_SUCCESS = 'SELLER_UPDATE_SUCCESS'
export const SELLER_PROFILE_UPDATE_FAIL = 'SELLER_UPDATE_FAIL'
export const SELLER_PROFILE_UPDATE_RESET = 'SELLER_UPDATE_RESET'


export const ADD_SELLER_DETAILS_REQUEST = 'ADD_SELLER_DETAILS_REQUEST'
export const ADD_SELLER_DETAILS_SUCCESS = 'ADD_SELLER_DETAILS_SUCCESS'
export const ADD_SELLER_DETAILS_FAIL = 'ADD_SELLER_DETAILS_FAIL'
export const ADD_SELLER_DETAILS_RESET = 'ADD_SELLER_DETAILS_RESET'

